import Head from 'next/head'
import Aside from '../components/Aside'
import Main from '../components/Main'
import styles from '../styles/Home.module.scss'
import LeftAside from '../components/home/LeftAside';
import Stories from '../components/home/Stories';
import InputForm from '../components/home/InputForm';
import Posts from '../components/home/Posts';
import { API_URL } from '../assets/data/pageData';


export async function getStaticProps () {
  const res = await fetch(`${API_URL}/posts`);
  const data = await res.json();

  return {
      props: {
          posts: data
      }
  }
}


export default function Home( {posts} ) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Aside>
        <LeftAside />
      </Aside>

      <Main>
        <Stories />
        <InputForm />
        <Posts posts={posts}/>
      </Main>

      <Aside>
        <h1>Right Aside for Home</h1>
      </Aside>
      
    </div>
  )
}
