import Head from 'next/head'
import Aside from '../components/Aside'
import Main from '../components/Main'
import styles from '../styles/Home.module.scss'
import LeftAside from '../components/home/LeftAside';



export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Aside>
        <LeftAside />
      </Aside>

      <Main>
        Content for home
      </Main>

      <Aside>
        <h1>Right Aside for Home</h1>
      </Aside>
      
    </div>
  )
}
